AWSTemplateFormatVersion: "2010-09-09"
Description: ECR Module

Parameters:
  Env:
    Type: String
  Name:
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${Env}-${Name}"
      EmptyOnDelete: true
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUrl:
    Value: !GetAtt Repository.RepositoryUri
